name: VITE CI/CD for Test
on:
   push:
      branches:
         - development
         - main
         - "feature/*"
         - "bug/*"
         - "hotfix/*"

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
              node-version: 20

         - name: Install Dependencies
           run: npm ci

         - name: ESLint Check
           run: npm run lint

         #  - name: Style Lint Check
         #    run: npm run stylelint

         - name: Prettier Check
           run: npm run lint

         - run: npm run build
